theme = "base16_transparent"
[editor]
bufferline = "multiple"
color-modes = true
completion-trigger-len = 1
end-of-line-diagnostics = "hint"
line-number = "relative"
[editor.auto-pairs]
"(" = ")"
"[" = "]"
"{" = "}"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
character = "┊"
render = true

[editor.inline-diagnostics]
cursor-line = "error"

[editor.lsp]
display-inlay-hints = true
display-messages = true
# display-signature-help-docs = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = [
    "mode",
    "spacer",
    "diagnostics",
    "version-control",
    "file-name",
    "read-only-indicator",
    "file-modification-indicator",
    "spinner",
]
right = ["file-encoding", "file-type", "selections", "position"]

[editor.whitespace.render]
tab = "all"

[keys.normal]
A-d = ["yank", "paste_after"]
C-q = ":bclose"
[keys.normal."q"]
l = "@yoconsole.log('<esc><left>pa'<left>:<right>,<esc><left>p<S-A>;<esc>"
q = "replay_macro"
